[input]
html_selector = "main"
base_directory = "output"

[[input.files]]
path = "acerca/index.html"
url = "/acerca/"
title = "Acerca"

[[input.files]]
path = "iniciando-con-kivy-python/index.html"
url = "/iniciando-con-kivy-python/"
title = "Iniciando con Kivy para desarrollo GUI"

[[input.files]]
path = "python-continue/index.html"
url = "/python-continue/"
title = "Palabra clave en Python: continue"

[[input.files]]
path = "python-else/index.html"
url = "/python-else/"
title = "Palabras clave en Python: else"

[[input.files]]
path = "python-break/index.html"
url = "/python-break/"
title = "Palabras clave en Python: break"

[[input.files]]
path = "python-assert/index.html"
url = "/python-assert/"
title = "Palabras clave en Python: assert"

[[input.files]]
path = "python-del/index.html"
url = "/python-del/"
title = "Palabras clave en Python: del"

[[input.files]]
path = "python-with/index.html"
url = "/python-with/"
title = "Palabras clave en Python: with"

[[input.files]]
path = "python-pass/index.html"
url = "/python-pass/"
title = "Palabras clave en Python: pass"

[[input.files]]
path = "python-lambda/index.html"
url = "/python-lambda/"
title = "Palabras clave en Python: lambda"

[[input.files]]
path = "python-import/index.html"
url = "/python-import/"
title = "Palabras clave en Python: import"

[[input.files]]
path = "python-as/index.html"
url = "/python-as/"
title = "Palabras clave en Python: as"

[[input.files]]
path = "python-palabras-clave/index.html"
url = "/python-palabras-clave/"
title = "Palabras clave en Python: ¿Cuáles son?"

[[input.files]]
path = "python-return/index.html"
url = "/python-return/"
title = "Palabras clave en Python: return"

[[input.files]]
path = "python-class/index.html"
url = "/python-class/"
title = "Palabras clave en Python: class"

[[input.files]]
path = "python-array/index.html"
url = "/python-array/"
title = "Estructuras de datos en Python: Arreglos (arrays)"

[[input.files]]
path = "python-while/index.html"
url = "/python-while/"
title = "Palabras clave en Python: while"

[[input.files]]
path = "gestionar-proyecto-python-uv/index.html"
url = "/gestionar-proyecto-python-uv/"
title = "Cómo gestionar un proyecto Python con uv?"

[[input.files]]
path = "python-for/index.html"
url = "/python-for/"
title = "Palabras clave en Python: for"

[[input.files]]
path = "python-if/index.html"
url = "/python-if/"
title = "Palabras clave en Python: if"

[[input.files]]
path = "python-def/index.html"
url = "/python-def/"
title = "Palabras clave en Python: def"

[[input.files]]
path = "python-and/index.html"
url = "/python-and/"
title = "Palabras clave en Python: and"

[[input.files]]
path = "python-true/index.html"
url = "/python-true/"
title = "Palabras clave en Python: True"

[[input.files]]
path = "python-none/index.html"
url = "/python-none/"
title = "Palabras clave en Python: None"

[[input.files]]
path = "python-false/index.html"
url = "/python-false/"
title = "Palabras clave en Python: False"

[[input.files]]
path = "obtener-ayuda-python/index.html"
url = "/obtener-ayuda-python/"
title = "Cómo obtener ayuda en Python?"

[[input.files]]
path = "ciclos-for-python/index.html"
url = "/ciclos-for-python/"
title = "Python a través de ejemplos: Ciclos o bucles for"

[[input.files]]
path = "comprimir-archivos-zipfile-python/index.html"
url = "/comprimir-archivos-zipfile-python/"
title = "Cómo comprimir archivos con zipfile en Python?"

[[input.files]]
path = "entorno-virtual-python/index.html"
url = "/entorno-virtual-python/"
title = "Cómo crear un entorno virtual de Python?"

[[input.files]]
path = "iniciando-con-pyside6-python/index.html"
url = "/iniciando-con-pyside6-python/"
title = "Iniciando con PySide6 para desarrollo GUI"

[[input.files]]
path = "condicionales-python/index.html"
url = "/condicionales-python/"
title = "Python a través de ejemplos: Sentencias condicionales"

[[input.files]]
path = "instalar-python-linux-debian-ubuntu/index.html"
url = "/instalar-python-linux-debian-ubuntu/"
title = "Cómo instalar Python en tu sistema operativo Debian o Ubuntu Linux?"

[[input.files]]
path = "iniciando-con-tkinter-python/index.html"
url = "/iniciando-con-tkinter-python/"
title = "Iniciando con Tkinter para desarrollo GUI"

[[input.files]]
path = "iniciando-con-pyqt-python/index.html"
url = "/iniciando-con-pyqt-python/"
title = "Iniciando con PyQt para desarrollo GUI"

[[input.files]]
path = "patron-mvc-python/index.html"
url = "/patron-mvc-python/"
title = "Patrones de diseño en Python: Modelo-Vista-Controlador (MVC)"

[[input.files]]
path = "expresiones-python/index.html"
url = "/expresiones-python/"
title = "Python a través de ejemplos: Expresiones"

[[input.files]]
path = "operadores-python/index.html"
url = "/operadores-python/"
title = "Python a través de ejemplos: Operadores"

[[input.files]]
path = "elementos-iguales-lista-python/index.html"
url = "/elementos-iguales-lista-python/"
title = "Cómo saber si todos los elementos en una lista son iguales en Python?"

[[input.files]]
path = "constantes-python/index.html"
url = "/constantes-python/"
title = "Python a través de ejemplos: Constantes"

[[input.files]]
path = "variables-python/index.html"
url = "/variables-python/"
title = "Python a través de ejemplos: Variables"

[[input.files]]
path = "valores-python/index.html"
url = "/valores-python/"
title = "Python a través de ejemplos: Valores"

[[input.files]]
path = "ejecutar-script-python/index.html"
url = "/ejecutar-script-python/"
title = "Cómo ejecutar un script Python?"

[[input.files]]
path = "instalar-python-windows/index.html"
url = "/instalar-python-windows/"
title = "Cómo instalar Python en tu sistema operativo Windows?"

[[input.files]]
path = "instalar-python-macos/index.html"
url = "/instalar-python-macos/"
title = "Cómo instalar Python en tu sistema operativo macOS?"

[[input.files]]
path = "python-hola-mundo/index.html"
url = "/python-hola-mundo/"
title = "Cómo escribir tu primer programa en Python: Hola, mundo!"
