[input]
html_selector = "main"
base_directory = "output"

[[input.files]]
path = "acerca/index.html"
url = "/acerca/"
title = "Acerca"

[[input.files]]
path = "contacto/index.html"
url = "/contacto/"
title = "Contacto"

[[input.files]]
path = "instalar-python-windows/index.html"
url = "/instalar-python-windows/"
title = "C칩mo instalar Python en tu sistema operativo Windows?"

[[input.files]]
path = "instalar-python-macos/index.html"
url = "/instalar-python-macos/"
title = "C칩mo instalar Python en tu sistema operativo macOS?"

[[input.files]]
path = "python-palabras-clave/index.html"
url = "/python-palabras-clave/"
title = "Palabras clave o reservadas de Python: cu치les son?"

[[input.files]]
path = "python-hola-mundo/index.html"
url = "/python-hola-mundo/"
title = "C칩mo escribir tu primer programa en Python: Hola, mundo!"
